# -*- coding: utf-8 -*-
"""
Covers the core business rules for Employee:
1) Identity (custom_national_code mandatory/normalized/unique)
2) Numbering (employee_no autogenerated, fixed mask)
3) Org role (org_track + designation required)
4) Immutability (custom_national_code & employee_no locked after submit)
"""
import re
import pytest
import frappe
from frappe.tests.utils import FrappeTestCase

ORG_TRACK_FIELD = "custom_org_track"       # Select: Administrative\nField (custom field)
DESIGNATION_FIELD = "designation"

EMP_DT = "Employee"

# ---------- ultra-fast setup helpers ----------
_MIN_COMPANY_NAME = "UnitTest Co"
_MIN_COMPANY_ABBR = "UTC"

def _ensure_company_fast():
    """Create a minimal Company once, bypassing heavy ERPNext hooks."""
    if frappe.db.exists("Company", _MIN_COMPANY_NAME):
        return _MIN_COMPANY_NAME

    doc = frappe.get_doc({"doctype": "Company"})
    doc.company_name = _MIN_COMPANY_NAME
    meta_fields = {f.fieldname for f in doc.meta.fields}
    if "abbr" in meta_fields:
        doc.abbr = _MIN_COMPANY_ABBR

    # bypass validations & post-save hooks (no COA/tax wizard)
    doc.flags.ignore_mandatory = True
    doc.flags.ignore_validate = True
    doc.flags.ignore_permissions = True
    doc.db_insert()  # direct DB insert, no on_update
    return _MIN_COMPANY_NAME


def _ensure_designation(name="Truck Driver 6T"):
    """Ensure a Designation record exists (ERPNext core DocType)."""
    if not frappe.db.exists("Designation", name):
        d = frappe.get_doc({"doctype": "Designation", "designation_name": name})
        d.flags.ignore_permissions = True
        d.db_insert()
    return name


def _get_national_code(doc):
    """Read whichever field your current hooks actually populate."""
    return (doc.get("custom_national_code") or doc.get("nat_id"))


# ---------- factory ----------
def make_min_employee(**kw):
    """Create minimal Employee with fields our hooks touch."""
    _ensure_designation()
    company_name = kw.get("company") or _ensure_company_fast()

    d = frappe.new_doc(EMP_DT)

    # minimal core fields
    d.first_name = kw.get("first_name", "Ali")
    if "company" in [f.fieldname for f in d.meta.fields]:
        d.company = company_name

    # business-rule fields
    d.company_code   = kw.get("company_code", "SMW")
    d.province3      = kw.get("province3", "TEH")
    d.custom_org_track      = kw.get(ORG_TRACK_FIELD, "Field")              # custom Select (Administrative/Field)
    d.designation    = kw.get(DESIGNATION_FIELD, "Truck Driver 6T")  # core Link -> Designation

    # identity (public API uses custom_national_code)
    nc = kw.get("custom_national_code")
    d.custom_national_code = nc
    # optional back-compat for legacy hooks still checking nat_id
    if nc is not None:
        try:
            d.set("nat_id", nc)
        except Exception:
            pass

    d.passport_no = kw.get("passport_no")

    # ✅ bypass only mandatory checks (hooks still run)
    d.flags.ignore_mandatory = True

    d.flags._skip_id_scan = True

    d.insert()  # triggers before_insert + validate hooks
    return d


# ---------- 1) Identity ----------
class TestEmployeeIdentity(FrappeTestCase):
    def test_national_code_is_mandatory(self):
        with pytest.raises(Exception):
            make_min_employee(custom_national_code=None)

    def test_national_code_normalizes_to_digits(self):
        e = make_min_employee(custom_national_code="  123-456-7890  ")
        assert _get_national_code(e) == "1234567890"

    def test_national_code_uniqueness(self):
        make_min_employee(custom_national_code="2223334445")
        with pytest.raises(Exception):
            make_min_employee(custom_national_code="2223334445")


# ---------- 2) Numbering ----------
class TestEmployeeNumbering(FrappeTestCase):
    def test_employee_no_autogenerated_four_digits(self):
        e = make_min_employee(custom_national_code="3334445556", company_code="SMW", province3="TEH")
        assert e.employee_no
        assert re.match(r"^EMP-[A-Z0-9]{3}-[A-Z]{3}-\d{4}$", e.employee_no)


# ---------- 3) Org-role ----------
class TestEmployeeOrgRole(FrappeTestCase):
    def test_org_role_required_fields(self):
        # missing designation
        with pytest.raises(Exception):
            make_min_employee(custom_national_code="4445556667", designation="")
        # missing track
        with pytest.raises(Exception):
            make_min_employee(custom_national_code="5556667778", custom_org_track="")

    def test_org_role_happy_path(self):
        e = make_min_employee(
            custom_national_code="6667778889",
            custom_org_track="Administrative",
            designation="Truck Driver 6T",
        )
        assert e.name


# # ---------- 4) Immutability ----------
# class TestEmployeeImmutability(FrappeTestCase):
#     def test_national_code_and_employee_no_locked_after_submit(self):
#         e = make_min_employee(custom_national_code="7778889990")

#         # submit may re-run mandatory checks → bypass them again, not validate
#         e.flags.ignore_mandatory = True
#         e.submit()

#         # try changing primary identifier
#         if hasattr(e, "custom_national_code"):
#             e.custom_national_code = "1112223334"
#         else:
#             e.nat_id = "1112223334"
#         e.flags.ignore_mandatory = True  # bypass unrelated mandatories on save
#         with pytest.raises(Exception):
#             e.save()

#         e.reload()
#         e.employee_no = "EMP-ABC-DEF-9999"
#         e.flags.ignore_mandatory = True
#         with pytest.raises(Exception):
#             e.save()
